### ISSUE TITLE
I can't seem to add audio it keeps giving me an error 

### ISSUE THREAD

**Issue by noborhys** [ShiromiyaG/RVC-AI-Cover-Maker-UI#2]
File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\gradio\blocks.py", line 1509, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\tabs\full_inference.py", line 160, in save_to_wav
    shutil.copy(file_path, target_path)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\shutil.py", line 427, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\shutil.py", line 266, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'audio_files\\original_files\\Thats_What_I_Like_-_Bruno_Mars_Lyrics-Vietsub.wav'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\gradio\route_utils.py", line 714, in __call__
    await self.app(scope, receive, send)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\starlette\routing.py", line 74, in app
    await response(scope, receive, send)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\starlette\responses.py", line 338, in __call__
    await send(
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\starlette\_exception_handler.py", line 48, in sender
    await send(message)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\starlette\_exception_handler.py", line 48, in sender
    await send(message)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\starlette\middleware\errors.py", line 162, in _send
    await send(message)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 503, in send
    output = self.conn.send(event=h11.Data(data=data))
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\h11\_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\h11\_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\h11\_writers.py", line 65, in __call__
    self.send_data(event.data, write)
  File "F:\RVC-AI-Cover-Maker-UI-1.0.2\env\lib\site-packages\h11\_writers.py", line 91, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length

**Comment by ShiromiyaG** [comment]
I've fixed what I can, it seems to have something to do with a bug in gradio, but now, at least, it's only buggy in the terminal. In other words, the audio is now being sent correctly to the folder where it should be sent
