### ISSUE TITLE
Can't use rvmpe

### ISSUE THREAD

**Issue by Lumaah** [ShiromiyaG/RVC-AI-Cover-Maker-UI#3]
An error occurred during audio conversion: [Errno 2] No such file or directory: 'programs\\applio_code\\rvc\\models\\predictors\\rmvpe.pt'
Traceback (most recent call last):
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\programs\applio_code\rvc\infer\infer.py", line 198, in convert_audio
    audio_opt = self.vc.pipeline(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\programs\applio_code\rvc\infer\pipeline.py", line 600, in pipeline
    pitch, pitchf = self.get_f0(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\programs\applio_code\rvc\infer\pipeline.py", line 344, in get_f0
    self.model_rmvpe = RMVPE0Predictor(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\programs\applio_code\rvc\lib\predictors\RMVPE.py", line 458, in __init__
    ckpt = torch.load(model_path, map_location="cpu")
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\torch\serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\torch\serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\torch\serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'programs\\applio_code\\rvc\\models\\predictors\\rmvpe.pt'

Traceback (most recent call last):
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\blocks.py", line 1509, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\core.py", line 630, in full_inference_program
    vocals_file = os.path.join(vocals_path, vocals_file)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

**Comment by Lumaah** [comment]
If i add myself rvmpe.pt to the predictors folder it works fine (i used precompiled version)

**Comment by ShiromiyaG** [comment]
Yes, I forgot that part about downloading the .rmvpe in the .bat, well, in the new run.bat and precompiled version, this has already been fixed. Thanks for letting me know!
