### ISSUE TITLE
Main Vocals are considered as Backing Vocals

### ISSUE THREAD

**Issue by Lumaah** [ShiromiyaG/RVC-AI-Cover-Maker-UI#4]
When testing multiple songs i noticed that the default settings make so that some main vocals are considered backing vocals and therefore are not being interfered

here is one exemple of a song where this happens
https://www.youtube.com/watch?v=WurwBthIO6g

also there's a typo in separating backing vocals
![image](https://github.com/user-attachments/assets/a0371ee3-cdd6-4138-ad9c-fd6daa996205)

**Comment by ShiromiyaG** [comment]
Hmm, I'll try to sort this song out, but I suspect it's the fault of the standard karaoke model, not the program itself

**Comment by ShiromiyaG** [comment]
Yeah, it's the fault of the karaoke models and how the song was mixed, what I can do is an option to infer the backing vocals as well

**Comment by Lumaah** [comment]
would be a nice feature to add

**Comment by Lumaah** [comment]
also i found another bug, if you interfer a song then try to interfer another one it will interfer the first one instead and not the new one

**Comment by ShiromiyaG** [comment]
> also i found another bug, if you interfer a song then try to interfer another one it will interfer the first one instead and not the new one

Can you try the latest commit? it might have fixed it

**Comment by Lumaah** [comment]
i just tried it, doesn't seem to resolve the issue

**Comment by Lumaah** [comment]
i don't have the delete audio option enabled if that could influence with how the program works

**Comment by ShiromiyaG** [comment]
> i don't have the delete audio option enabled if that could influence with how the program works

Yes, that was probably the problem, but I think I've fixed it now with that option disabled, I'll wait for your feedback

**Comment by Lumaah** [comment]
Making RVC inference
Converting audio 'None'...
An error occurred during audio conversion: 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\programs\applio_code\rvc\infer\infer.py", line 122, in convert_audio
    audio = load_audio_infer(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\programs\applio_code\rvc\lib\utils.py", line 49, in load_audio_infer
    file = file.strip(" ").strip('"').strip("\n").strip('"').strip(" ")
AttributeError: 'NoneType' object has no attribute 'strip'

Traceback (most recent call last):
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\blocks.py", line 1509, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\core.py", line 729, in full_inference_program
    vocals_file = os.path.join(vocals_path, vocals_file)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

looks like it broke even more

**Comment by Lumaah** [comment]
Traceback (most recent call last):
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\blocks.py", line 1509, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\core.py", line 356, in full_inference_program
    os.rename(
FileExistsError: [WinError 183] Impossible de créer un fichier déjà existant: 'E:\\Apps\\RVC-AI-Cover-Maker-UI-v1.0.3\\audio_files\\vocals\\SUBTERFUGE WITH LYRICS ｜ FNF SONIC LEGACY Cover_instrumental.flac' -> 'E:\\Apps\\RVC-AI-Cover-Maker-UI-v1.0.3\\audio_files\\instrumentals\\instrumentals.flac'

got this too

**Comment by ShiromiyaG** [comment]
I just found the problem, I was looking for the full name of the file instead of just part of the name. I think I've fixed it now

**Comment by Lumaah** [comment]
nope, installed the latest commit and got this

File not found: audio_files\original_files\SUBTERFUGE WITH LYRICS ｜ FNF SONIC LEGACY Cover.m4a
Traceback (most recent call last):
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\blocks.py", line 1509, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\core.py", line 359, in full_inference_program
    os.path.join(store_dir, search_with_word(store_dir, "instrumental")),
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

however after refreshing the whole page it worked

**Comment by ShiromiyaG** [comment]
I've made some changes, it's supposed to have fixed this

**Comment by Lumaah** [comment]
yeah, i can confirm its fixed, and thanks for the interfer backing vocals option.
