### ISSUE TITLE
Wrong Backing Vocals Interfer Track

### ISSUE THREAD

**Issue by Lumaah** [ShiromiyaG/RVC-AI-Cover-Maker-UI#6]
Final merged song doesn't have the correct backing vocals interfer track

Steps to reproduce this

- Interfer the first song, with the interfer backing track option enabled, and the delete audio option disabled
- Interfer the second with the same conditions
- Voila

**Comment by Lumaah** [comment]
I potentially have a fix for this, it would require that for each music there is a different folder with the name of the music.
for example, if the music was Despacito, the audio_files folder would look like this

audio_files/Despacito/folders

i think that should prevent the wrong music from being merged

**Comment by ShiromiyaG** [comment]
@Lumaah  Okay, I've changed the code to create folders for each song, I'll wait for your feedback

**Comment by Lumaah** [comment]
I got this error right after it completed interfering the backing track

Traceback (most recent call last):
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\blocks.py", line 1509, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\core.py", line 883, in full_inference_program
    vocals_file = os.path.join(vocals_path, vocals_file)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

**Comment by ShiromiyaG** [comment]
Oops, sorry, I think I've fixed it now

**Comment by Lumaah** [comment]
Yup, it's fixed and fully working now, thanks.
But i wanted to know, if you could maybe add a way to interfer with another model the backing track ?

**Comment by ShiromiyaG** [comment]
> Yup, it's fixed and fully working now, thanks. But i wanted to know, if you could maybe add a way to interfer with another model the backing track ?

Hmmmm good idea, I'll do it

**Comment by ShiromiyaG** [comment]
@Lumaah I've added it, I'll wait for your feedback

**Comment by Lumaah** [comment]
Worked without any flaws, it justs missing a different pitch option for the backing vocals and it would be perfect.

**Comment by ShiromiyaG** [comment]
> Worked without any flaws, it justs missing a different pitch option for the backing vocals and it would be perfect.

Added

**Comment by Lumaah** [comment]
When you convert multiple times the same audio (without the delete audio enabled) it will give you this error about the reverb file

Traceback (most recent call last):
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\blocks.py", line 1509, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\core.py", line 603, in full_inference_program
    os.rename(

**Comment by Lumaah** [comment]
also the backing interfer settings works perfectly fine

**Comment by ShiromiyaG** [comment]
> When you convert multiple times the same audio (without the delete audio enabled) it will give you this error about the reverb file
> 
> Traceback (most recent call last): File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\queueing.py", line 532, in process_events response = await route_utils.call_process_api( File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api output = await app.get_blocks().process_api( File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\blocks.py", line 1923, in process_api result = await self.call_function( File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\blocks.py", line 1509, in call_function prediction = await anyio.to_thread.run_sync( File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync return await get_async_backend().run_sync_in_worker_thread( File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio_backends_asyncio.py", line 2177, in run_sync_in_worker_thread return await future File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio_backends_asyncio.py", line 859, in run result = context.run(func, *args) File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\utils.py", line 832, in wrapper response = f(*args, **kwargs) File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\core.py", line 603, in full_inference_program os.rename(

Can you send me the full error?

**Comment by Lumaah** [comment]
that's the full error, it only showed me this in the terminal

**Comment by ShiromiyaG** [comment]
I've changed the code, now it's supposed to be showing the error

**Comment by Lumaah** [comment]
Traceback (most recent call last):
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\blocks.py", line 1509, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\core.py", line 611, in full_inference_program
    os.rename(
FileExistsError: [WinError 183] Impossible de créer un fichier déjà existant: 'E:\\Apps\\RVC-AI-Cover-Maker-UI-v1.0.3\\audio_files\\Gumi Eng. & Yohioloid ⧸ The Chattering Lack of Common Sense [Original Song]\\dereverb\\Gumi Eng. & Yohioloid ⧸ The Chattering Lack of Common Sense [Original Song]_vocals_karaoke_(No Reverb)_UVR-DeEcho-DeReverb.flac' -> 'E:\\Apps\\RVC-AI-Cover-Maker-UI-v1.0.3\\audio_files\\Gumi Eng. & Yohioloid ⧸ The Chattering Lack of Common Sense [Original Song]\\dereverb\\Gumi Eng_noreverb.flac'

That's all i can get

**Comment by Lumaah** [comment]
i think it exceeds the maximum path limit

**Comment by ShiromiyaG** [comment]
It's saying that the error is because the file already exists. I think I did a temp fix

**Comment by Lumaah** [comment]
nope still the same exact error

Traceback (most recent call last):
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\blocks.py", line 1509, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\env\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "E:\Apps\RVC-AI-Cover-Maker-UI-v1.0.3\core.py", line 663, in full_inference_program
    os.rename(
FileExistsError: [WinError 183] Impossible de créer un fichier déjà existant: 'E:\\Apps\\RVC-AI-Cover-Maker-UI-v1.0.3\\audio_files\\Gumi Eng. & Yohioloid ⧸ The Chattering Lack of Common Sense [Original Song]\\deecho\\Gumi Eng_noreverb_(No Echo)_UVR-De-Echo-Normal.flac' -> 'E:\\Apps\\RVC-AI-Cover-Maker-UI-v1.0.3\\audio_files\\Gumi Eng. & Yohioloid ⧸ The Chattering Lack of Common Sense [Original Song]\\deecho\\Gumi Eng_noecho.flac'

**Comment by ShiromiyaG** [comment]
You got the same error, only on another line that has the same type of code. I've changed the logic a bit, now it's to check if the files really exist

**Comment by Lumaah** [comment]
Does work now, thanks.

**Comment by Lumaah** [comment]
wrong button my bad

**Comment by ShiromiyaG** [comment]
Np lol
